export const sidoRegions = [
  { name: '서울', code: 'seoul', regionCode: '11' },
  { name: '부산', code: 'busan', regionCode: '26' },
  { name: '대구', code: 'daegu', regionCode: '27' },
  { name: '인천', code: 'incheon', regionCode: '28' },
  { name: '광주', code: 'gwangju', regionCode: '29' },
  { name: '대전', code: 'daejeon', regionCode: '30' },
  { name: '울산', code: 'ulsan', regionCode: '31' },
  { name: '세종', code: 'sejong', regionCode: '36' },
  { name: '경기', code: 'gyeonggi', regionCode: '41' },
  { name: '강원', code: 'gangwon', regionCode: '42' },
  { name: '충북', code: 'chungbuk', regionCode: '43' },
  { name: '충남', code: 'chungnam', regionCode: '44' },
  { name: '전북', code: 'jeonbuk', regionCode: '45' },
  { name: '전남', code: 'jeonnam', regionCode: '46' },
  { name: '경북', code: 'gyeongbuk', regionCode: '47' },
  { name: '경남', code: 'gyeongnam', regionCode: '48' },
  { name: '제주', code: 'jeju', regionCode: '50' },
];
