name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and push Docker image
      run: |
        docker build -t chany91/bbansrun-fe:latest .
        docker push chany91/bbansrun-fe:latest

    - name: Deploy to server
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SERVER_IP: ${{ secrets.SERVER_IP }}
        GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
      run: |
        echo "${SSH_PRIVATE_KEY}" > deploy_key
        chmod 600 deploy_key
        ssh -o StrictHostKeyChecking=no -i deploy_key ubuntu@${SERVER_IP} << 'EOF'
          set -e

          # 기존 포트 확인
          PORT=3000
          while lsof -i:$PORT > /dev/null; do
            echo "Port $PORT is in use, incrementing..."
            PORT=$((PORT+1))
          done

          echo "Using port $PORT for the new container."

          # 새로운 컨테이너 실행
          docker-compose up -d --no-deps -p bbansrun-fe -e "FRONTEND_PORT=$PORT"

          # 이전 컨테이너 중지 및 제거
          if [ $PORT -gt 3000 ]; then
            OLD_PORT=$((PORT-1))
            docker stop bbansrun-fe-$OLD_PORT || true
            docker rm bbansrun-fe-$OLD_PORT || true
          fi
        EOF
